[manifest]
version = "0.0.1"
dump_lua = true
priority = 1000

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = "DARK_EDITION = {0,0,0,1},"
position = "after"
payload = """
DANDYRED = HEX("c36063"),
DANDYORANGE = HEX("ce9153"),
DANDYYELLOW = HEX("cfcc59"),
DANDYGREEN = HEX("5ecc59"),
DANDYBLUE = HEX("5c90ca"),
DANDYPURPLE = HEX("854ecd"),
"""
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "dark_edition = G.C.DARK_EDITION,"
position = "after"
payload = """
dandy_red = G.C.DANDYRED,
dandy_orange = G.C.DANDYORANGE,
dandy_yellow = G.C.DANDYYELLOW,
dandy_green = G.C.DANDYGREEN,
dandy_blue = G.C.DANDYBLUE,
dandy_purple = G.C.DANDYPURPLE,
"""
match_indent = true